### ISSUE TITLE
Have to re-initialize constantly, daily

### ISSUE THREAD

**Issue by magyartj** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#201]
My Alexa Routine nodes are constantly asking me to "open http://192.168.1.9:3456 in your browser", that IP being the IP address of my Home Assistant install. I go to that webpage in a browser and enter my Amazon username/password and then it tells me "Amazon Alexa Cookie successfully retrieved. You can close the browser.". It then starts working, but within a day, I notice my Alexa isn't speaking again. Have to do it all over again.

I see this in the Node-Red Add-On log during startup:

```
13 Sep 13:26:59 - [warn] [alexa-remote-account:66fb228ef256d965] ENOENT: no such file or directory, open 'authorizationAlexa'
13 Sep 13:26:59 - [info] [alexa-remote-account:66fb228ef256d965] intialising with the PROXY method and NO saved data...
13 Sep 13:26:59 - [warn] [alexa-remote-account:66fb228ef256d965] open http://192.168.1.9:3456 in your browser
```

And then when a flow triggers that tries to use it, I see this:

`13 Sep 13:39:47 - [error] [alexa-remote-routine:Alexa Speak Living Room Only] Account not initialised!`

After I go to the URL and log in, I see this in the log:

`13 Sep 13:59:38 - [info] [alexa-remote-account:66fb228ef256d965] intialising with the PROXY method and saved data...`

I never see a "Success" message or anything else, which there should be a log entry whether it succeeds or fails. Anyway.

It's quite an annoyance to have to do this daily. I don't exactly recall when this started happening, but I would estimate about 2-3 months ago; I have been procrastinating to figure out a solution until now. And I haven't found one.

**Comment by Babelbernd** [comment]
Same here, every 24 hours i have to re-initialize. @bbindreiter is there any workaround for this issue?

**Comment by alanthewild** [comment]
Same here, every 24 hours, which sadly makes this add-on next to useless for me. I'm guessing Amazon changed something in the login process? @bbindreiter any ideas on how to resolve this?

**Comment by bbindreiter** [comment]
@magyartj to me it looks like the file the cookie is saved to is not persisted? Is the file there when it asks you to reinitialize? 

I am reinitializing every 12 hours in my node-red instance and haven't noticed any problem (so far). Doing that for years now. 

I am sorry but this solution will never work reliability and it can break every day over and over again.. 😭

**Comment by Babelbernd** [comment]
Here the file ist there, i remember i had to create the file and add the cookie-text. Is it still working like that or should the file be created itself after receiving the cookie from the Login amazon Website?

**Comment by DeepflashX** [comment]
I am having most likely a permission problem. Whatever folder I put in the file field, I get some error:
"ENOENT: no such file or directory, open '/home/dietpi/alexa.txt'"
The authorization itself works, but is gone after redeploying something.

**Comment by bernardesarthur** [comment]
I have the exact same problem, I don't know what to do. I don't have a problem with file permissions, I check that. Anyone can help?

**Comment by bernardesarthur** [comment]
I had the same problem. I used the server from ***amazon.com.br** and I change that to ***amazon.com** and works.

**Comment by earto** [comment]
> Same here and now after the "Amazon Alexa Cookie successfully retrieved. You can close the browser." message the node still send's me the "go to your ip :3456" link, I have repeataed this process like 5 times and it won't login.
> 
> what do I put on the "file path" field? maybe my cookie is not being saved or something?

For Node-Red on Home Assistant the file path must be one of the core shared directories. I use /share since its designed for this purpose. Follow these steps:

1. Install the [Samba app](https://www.home-assistant.io/common-tasks/os/#installing-and-using-the-samba-app) if you don't have it already.
2. Open Windows Explorer to \\<home-assistant-ip\share. Create folder "node-red". Inside "node-red" folder create an empty file called "alexa-cookie.json".
3. In the Alexa Account Node set the path to `/share/node-red/alexa-cookie.json`

**Comment by earto** [comment]
If you receive error `ENOENT: no such file or directory` then follow the steps in the [above post](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/201#issuecomment-4231255048).

After the initial login, you can confirm that alexa-cookie.json contains the login cookie.

**Comment by magyartj** [comment]
@earto  That was great info in regards to setting up the alexa cookie JSON file. It helped! I added the empty file like you said  and then added that to the node configuration in the "File Path" field of the Edit Alexa Account Node. I then opened my browser to the address and typed in my credentials. It was the first time in forever that I got a success message. I then noticed the cookie file was 7kb and there was text added to it! But unfortunately, its still not working. In the Node-Red app log in HA:

```
14 Apr 21:40:00 - [warn] [alexa-remote-account:66fb228ef256d965] Unexpected end of JSON input
14 Apr 21:40:00 - [info] [alexa-remote-account:66fb228ef256d965] intialising with the PROXY method and NO saved data...
14 Apr 21:40:00 - [warn] [alexa-remote-account:66fb228ef256d965] open http://192.168.1.9:3456 in your browser\
```

Then there are a numerous of these messages (notice it switched from "NO saved data" to "saved data":
```
14 Apr 21:42:25 - [info] [alexa-remote-account:66fb228ef256d965] intialising with the PROXY method and saved data...
```
And then:
```
14 Apr 21:42:27 - [error] [alexa-remote-routine:e698380afe56cad9] Account not initialised!
```
And then 100+ more of these:
```
14 Apr 21:42:25 - [info] [alexa-remote-account:66fb228ef256d965] intialising with the PROXY method and saved data...
```

The Node Red nodes now all say "init with proxy" below them. Not sure what to do with that.

**Comment by magyartj** [comment]
Update: So that above went on for another 20 minutes or so and then this:

```
14 Apr 22:03:39 - [info] [alexa-remote-account:66fb228ef256d965] intialising with the PROXY method and saved data...
14 Apr 22:03:50 - [error] [alexa-remote-init:6f7cbe7657fa02cc] Timeout
TCP 192.168.1.81:9999 Error: TCP Timeout after 15000ms
192.168.1.81:9999 {"emeter":{"get_realtime":{}},"schedule":{"get_next_action":{}},"system":{"get_sysinfo":{}},"cnCloud":{"get_info":{}}}
    at Timeout._onTimeout (/config/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (node:internal/timers:605:17)
    at processTimers (node:internal/timers:541:7)
[Barn Shop Fans Switch] device.send() Error: TCP Timeout after 15000ms
192.168.1.81:9999 {"emeter":{"get_realtime":{}},"schedule":{"get_next_action":{}},"system":{"get_sysinfo":{}},"cnCloud":{"get_info":{}}}
    at Timeout._onTimeout (/config/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (node:internal/timers:605:17)
    at processTimers (node:internal/timers:541:7)
15 Apr 02:08:12 - [error] [alexa-remote-routine:Alexa Speak] Account not initialised!
```

But then, suddenly it started working and this appears in the log!:

`15 Apr 11:39:41 - [info] [alexa-remote-routine:Alexa Speak Multiple] request:...
`

That was about 13-14 hours after I tried to initialize it, and about 9hrs after the last "Account not initialised!" message. Been working great since. No idea why it took so long to initialize, but at least it is working now and I'm happy. 

The advise about setting up the file in the /share directory was money, thanks @earto !

**Comment by earto** [comment]
Appreciate the update @magyartj !

I've also run into problems where intermittently, I receive "Account not initialised" or some other error I can't recall. In those cases I can trigger the update again immediately and it usually works the second time. I think there's something funky with how Amazon handle this since its not an official API. Or maybe it updates the auth.

P.S. You probably noticed that PUSH events towards the Alexa Event Node (e.g. On Device Activity) work a few times after startup and then stop after a short time. This is mentioned in many other posts. Based on my testing, it appears to be an issue at the Amazon end, but I'm no expert! The only functional workaround for me (so far) is to trigger an action node periodically to GET the items (in my case Shopping List) every 10 mins.
